### ISSUE TITLE
💡 Feature request: landing page for NSFW subreddit when NSFW posts are disabled

### ISSUE THREAD

**Issue by Daniel-Valentine** [ferritreader/ferrit#13]
Builds off spikecodes/libreddit#508 and #9. For subreddits that Reddit deems totally NSFW, we should have a landing page for NSFW subreddits that show nothing else but a message to tell the user to turn _Show NSFW posts_ on if they want to view its contents. We can determine whether to do this in the JSON for `/r/:subreddit/about.json`, which we have to fetch anyway to show the subreddit info on the right; in that object, `.data.over18` will be `true`.

**Comment by sigaloid** [comment]
Should this simply replace the code added in the PR? I doubt there will be a sub which has all posts NSFW but isn't deemed NSFW itself by reddit. And if so, I don't think it would be wrong to say "this sub is NSFW" even if _technically_ reddit doesn't consider it NSFW. In practice they will still want to simply enable it in settings.

**Comment by sigaloid** [comment]
What do you think of this banner message?

`r/{{ sub.name }} is an NSFW sub, but you have "Show NSFW posts" disabled in <a href="/settings">settings</a>! Enable it to view this subreddit.`
