### ISSUE TITLE
💡 Feature request: SFW-only instances

### ISSUE THREAD

**Issue by sphars** [ferritreader/ferrit#23]
This issue is an existing request in [libreddit (#465)](https://github.com/spikecodes/libreddit/issues/465) and so I'm repeating the same request here. Thanks for picking up the new fork!

## Is your feature request related to a problem? Please describe.
If you want to make a network SFW, there isn't a way to block Reddit's NSFW content at DNS level. The administrator either has to go to more involved solutions such as a proxy, or block the entire website. [Here](https://libredd.it/r/ideasfortheadmins/comments/5jrz1x/i_am_a_sysadmin_for_schools_i_dont_want_to_block/) - [some](https://libredd.it/r/pihole/comments/p2g3k4/i_need_to_block_specific_subreddits_internetwide/) - [examples](https://libredd.it/r/HomeNetworking/comments/myqas1/blocking_nsfw_subreddits_with_opendns/).

## Describe the feature you would like to be implemented
Libreddit could have an environmental variable on the backend to allow/disallow serving NSFW content. If disabled, NSFW content would be filtered out at the backend and the toggle on the settings page would be missing.

This way, there would be SFW-only Libreddit instances, besides the current NSFW-allowed ones. If wanted, the same domain could serve both versions on different subdomains.

The network administrator could then proceed to block reddit.com as well as Libreddit's NSFW instances. The users could access Reddit content normally through Libreddit SFW instances.

## Describe alternatives you've considered
None.

## Additional context / screenshot
None.

**Comment by sphars** [comment]
Thanks @Daniel-Valentine and @sigaloid for your work on this :) Just pulled the latest commit, built the docker container and 
set the variable. Works great.

Just a little reminder to update the [wiki page](https://github.com/ferritreader/ferrit/wiki/Building,-Installation,-and-Deployment#settings-overrides-in-the-environment) about how to set the environment variable for future reference (would do it myself if I had write access)

**Comment by Daniel-Valentine** [comment]
Thanks for the reminder. I'll add the change to the wiki page.
