### ISSUE TITLE
💡 Feature request: Adding a donation button next to the top right corner buttons

### ISSUE THREAD

**Issue by Midou36O** [ferritreader/ferrit#49]
## Is your feature request related to a problem? Please describe.
n/a

## Describe the feature you would like to be implemented
Add a donation button next to the top right corner buttons, this can be used either to contribute to the project, or help funding instances (if they wish to add it.)

## Describe alternatives you've considered
n/a

## Additional context / screenshot
Something similar to this
![image](https://user-images.githubusercontent.com/45198486/197210924-27ed8e84-a697-4753-9b48-3b17c99f5ee9.png)

**Comment by Daniel-Valentine** [comment]
While I appreciate the sentiment, I will not be doing this. [Per the wiki, the project does not accept donations:](https://github.com/ferritreader/ferrit/wiki/FAQ/04d80395e6907c6fe9ba76fb8beb0425ba7b6d74#do-you-accept-donations)

> ### Do you accept donations?
>
> **No.** Ferrit does not accept donations. The best way to support the project is to contribute by adding code or raising issues. **Anyone who purports to represent Ferrit and solicits donations for the project is committing fraud.**

I may add the ability for an instance to add a "Hosted by" link somewhere in the page or on another page, but that's about the extent I would go with this.
